### ISSUE TITLE
docker: no matching manifest for unknown in the manifest list entries. — armhf Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by maxiride** [jessestuart/caddy-multiarch#1]
Hi, I've tried to deploy your caddy image on my Raspberry Pi 3 (`armhf`) but it failed:
```
pi@raspberrypi:~ $ docker run -d -p 2015:2015 jessestuart/caddy
Unable to find image 'jessestuart/caddy:latest' locally
latest: Pulling from jessestuart/caddy
docker: no matching manifest for unknown in the manifest list entries.
See 'docker run --help'.
```
From the [docker hub](https://hub.docker.com/r/jessestuart/caddy) page it is mentioned that is is compatible with `armhf` so I really don't know what the issue could be.

If I can provide any other infos to help debug let me know.

### Edit
I've also tried to clone the repo and build the image myself, here is the output from the console: [https://pastebin.com/fvpmetLs](https://pastebin.com/fvpmetLs)

The _interesting part_ if I understood correctly output is:
```
standard_init_linux.go:207: exec user process caused "exec format error"
The command '/bin/sh -c export GOARCH=$GOARCH &&     go get -v github.com/abiosoft/parent &&     VERSION=${version} PLUGINS=${plugins} ENABLE_TELEMETRY=true /usr/bin/builder.sh' returned a non-zero code: 1
```

### Edit 2
> docker: no matching manifest for unknown in the manifest list entries.

Might it be that you expect an `armhf` to be reported while instead `uname -a` returns `armv71`?
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
```

**Comment by jessestuart** [comment]
Hey @Maxiride —
Apologies for the delayed response; you're correct that this image was failing to build for `armhf` and `arm64` for a period due to upstream changes. Luckily, after a bit of head scratching, I've got things back up and running with nightly builds on all three platforms. Manifest is all up to date:

```console
λ docker manifest inspect jessestuart/caddy | jq '.manifests | .[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux"
}
```

...and I've verified the image runs smoothly on the nearest `arm64` device I had lying around (a Rock64, in this case). Let me know if if you have any issues with the updated image!
